# Generated by Django 4.2.3 on 2023-07-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursebuilder', '0004_assignment_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='grade',
        ),
    ]
