# Generated by Django 4.2.3 on 2023-07-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursebuilder', '0005_remove_assignment_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursebuilder.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursebuilder.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursebuilder.userprofile')),
            ],
        ),
    ]
