# Generated by Django 3.2.3 on 2023-07-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursebuilder', '0008_auto_20230723_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersname',
            name='link',
        ),
        migrations.RemoveField(
            model_name='membersname',
            name='semester',
        ),
    ]
